name: Task Request
description: Submit a task for Copilot to work on
title: "Make a report that ..."
labels: []
body:
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Explain why this task is needed
      placeholder: Describe the motivation, problem, or use case
    validations:
      required: true
  
  - type: textarea
    id: how
    attributes:
      label: How?
      description: Describe what needs to be done
      placeholder: Provide detailed steps or requirements for completing this task, remember you can always edit the issue later.
    validations:
      required: true
