name: Task Request
description: Submit a task for Copilot to work on
title: "[Task]: "
labels: []
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: A brief title for the task
      placeholder: e.g., Add feature X or Fix bug Y
    validations:
      required: true
  
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Explain why this task is needed
      placeholder: Describe the motivation, problem, or use case
    validations:
      required: true
  
  - type: textarea
    id: task
    attributes:
      label: Task
      description: Describe what needs to be done
      placeholder: Provide detailed steps or requirements for completing this task, remember you can always edit the issue later.
    validations:
      required: true
